# Generated by Django 3.2.20 on 2023-08-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('conference', 'conference'), ('seminar', 'seminar'), ('company party or meeting', 'company party or meeting'), ('product or service launch', 'product or service launch'), ('wedding', 'wedding'), ('festival', 'festival'), ('exhibition', 'exhibition'), ('charity event', 'charity event'), ('sport and competition', 'sport and competition')], max_length=50)),
                ('event_date', models.DateTimeField()),
                ('event_description', models.TextField()),
            ],
        ),
    ]
