# Generated by Django 3.2.20 on 2023-08-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DONE', 'DONE'), ('UNKNOWN', 'UNKNOWN'), ('CANCELLED', 'CANCELLED')], default='UNKNOWN', max_length=50),
        ),
    ]
